name: cross_classify
description: The Cross Classify Flutter SDK.
version: 0.9.2
homepage: https://github.com/crossclassify/xc-sdk-flutter
repository: https://github.com/crossclassify/xc-sdk-flutter
issue_tracker: https://github.com/crossclassify/xc-sdk-flutter/issues
topics:
  - cross-classify
  - analytics

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  device_info_plus: ^9.1.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  matomo_tracker_enhanced: ^4.2.2
#  uuid: ^4.1.0
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  uuid: ^3.0.7

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
